// <auto-generated />
using DotNetCoreProject.Model.New;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetCoreProject.Migrations.RuDeDict
{
    [DbContext(typeof(RuDeDictContext))]
    [Migration("20180814141300_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("DotNetCoreProject.Model.AndroidMetaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Locale")
                        .HasColumnName("locale");

                    b.HasKey("Id");

                    b.ToTable("android_metadata");
                });

            modelBuilder.Entity("DotNetCoreProject.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("NameId")
                        .HasColumnName("nameId");

                    b.HasKey("Id");

                    b.ToTable("category");
                });

            modelBuilder.Entity("DotNetCoreProject.Model.New.CategoryName", b =>
                {
                    b.Property<int>("IdCategoryName")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idCategoryName");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.HasKey("IdCategoryName");

                    b.ToTable("categoryName");
                });

            modelBuilder.Entity("DotNetCoreProject.Model.New.CategoryWord", b =>
                {
                    b.Property<int>("IdWord")
                        .HasColumnName("idWord");

                    b.Property<int>("IdCategory")
                        .HasColumnName("idCategory");

                    b.Property<string>("Definition")
                        .HasColumnName("definition");

                    b.Property<string>("Description")
                        .HasColumnName("description");

                    b.HasKey("IdWord", "IdCategory");

                    b.ToTable("categoryWord");
                });

            modelBuilder.Entity("DotNetCoreProject.Model.New.Word", b =>
                {
                    b.Property<int>("IdWord")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idWord");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<int>("PartGenus")
                        .HasColumnName("partGenus");

                    b.Property<string>("Plural")
                        .HasColumnName("plural");

                    b.HasKey("IdWord");

                    b.ToTable("word");
                });

            modelBuilder.Entity("DotNetCoreProject.Model.New.WordCategory", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idCategory");

                    b.Property<int>("IdCategoryName")
                        .HasColumnName("idCategoryName");

                    b.Property<int>("IdWord")
                        .HasColumnName("idWord");

                    b.HasKey("IdCategory");

                    b.ToTable("wordCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
