// <auto-generated />
using DotNetCoreProject.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetCoreProject.Migrations
{
    [DbContext(typeof(RussianGermanDictionaryContext))]
    partial class RussianGermanDictionaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("DotNetCoreProject.Model.AndroidMetaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Locale")
                        .HasColumnName("locale");

                    b.HasKey("Id");

                    b.ToTable("android_metadata");
                });

            modelBuilder.Entity("DotNetCoreProject.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("NameId")
                        .HasColumnName("nameId");

                    b.HasKey("Id");

                    b.ToTable("category");
                });

            modelBuilder.Entity("DotNetCoreProject.Model.CategoryName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categorynamen");
                });

            modelBuilder.Entity("DotNetCoreProject.Model.CategoryWord", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idCategory");

                    b.Property<string>("Definition")
                        .HasColumnName("Omschrijving");

                    b.Property<string>("Description")
                        .HasColumnName("vooromschrijving");

                    b.Property<int>("IdWord")
                        .HasColumnName("idWoord");

                    b.HasKey("IdCategory");

                    b.ToTable("categorywoord");
                });

            modelBuilder.Entity("DotNetCoreProject.Model.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<string>("Part")
                        .HasColumnName("deel");

                    b.HasKey("Id");

                    b.ToTable("woord");
                });

            modelBuilder.Entity("DotNetCoreProject.Model.WordCategory", b =>
                {
                    b.Property<int>("IdWord")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idWoord");

                    b.Property<string>("IdCategory")
                        .HasColumnName("idCategory");

                    b.HasKey("IdWord");

                    b.ToTable("woordcategory");
                });
#pragma warning restore 612, 618
        }
    }
}
